### ISSUE TITLE
How to install NPAPI-SDK?

### ISSUE THREAD

**Issue by fishon-dev** [GITNE/icedtea-web#17]
I'm getting this error when running ./configure;

configure - Copy: error: Package requirements (mozilla-plugin) were not met:
Package 'mozilla-plugin', required by 'virtual:world', not found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables MOZILLA_CFLAGS
and MOZILLA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

How do I install the npapi-sdk mentioned in the README in Cygwin?

**Comment by GITNE** [comment]
There is no NPAPI SDK, at least none that I am aware of, since the NPAPI has been declared in just a bunch of header files.

The NPAPI is declared as part of [XULRunner](https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XULRunner). You can download the latest version from Mozilla's FTP server and then just unpack it to wherever you see fit.

Since this is not an issue of IcedTea-Web but pertains to software distribution of a dependency, I am closing this issue.
